name: agree_n
description: A coffee trading platform

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.13.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.15
  firebase_analytics: ^7.0.1
  dio: 3.0.10
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  get: ^3.26.0
  get_storage: ^1.4.0
  pull_to_refresh: 1.6.3
  form_field_validator: ^1.0.1
  timeago: ^2.0.29
  flutter_rounded_date_picker: ^1.0.5
  webview_flutter: ^1.0.7
  geolocator: ^6.1.14
  dash_chat: ^1.1.15
  image_picker: ^0.6.7+21
  file_picker: ^1.13.3
  intl: ^0.16.1
  advance_pdf_viewer: ^1.2.2
  flutter_datetime_picker: ^1.5.0
  carousel_slider: ^3.0.0
  flutter_native_splash: ^0.3.0
  smooth_star_rating: ^1.1.1
  fl_chart: ^0.12.3
  shape_of_view: ^1.0.2
  xml: ^4.5.1
  html: ^0.14.0+4
  url_launcher: ^5.7.10
  photo_view: ^0.10.1
  flutter_swiper: ^1.1.6
  web_socket_channel: ^1.2.0
  horizontal_data_table: 2.5.0
  flag: ^3.2.2
  percent_indicator: ^2.1.9+1
  flutter_xlider: ^3.4.0
  pin_code_fields: ^6.1.0
  currency_text_input_formatter: ^1.0.4
  keyboard_actions: ^3.3.0
  extended_image: ^3.0.0-non-null-safet
  intl_phone_number_input: ^0.6.0
  connectivity: ^2.0.2
  flutter_app_badger: ^1.1.0
  easy_localization: ^2.3.3
  xml2json: ^4.4.0
  flutter_slidable: ^0.5.7
  swipe_gesture_recognizer: ^0.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  json_annotation: ^3.1.0
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  faker: ^1.3.0

flutter_launcher_name:
  name: "Agree-n"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher.png"

get_cli:
  separator: "."

flutter_native_splash:
  color: "#ffffff"
#  image: "assets/images/splash_bg.jpg"
#  fullscreen: true
#  android_gravity: fill
#  ios_content_mode: scaleToFill

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locales/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages